services:
  # app:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #       restart: true
  #   ports:
  #     - "3000:3000"
  #     - "5555:5555"
  #   volumes:
  #     - .:/app - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=${DATABASE_URL}
  db:
    image: postgres:17.2-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=ses
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - localstack_data:/var/lib/localstack
volumes:
  db:
    driver: local
  localstack_data:
    driver: local
